### PR TITLE
briefer chair selection: by consensus

### PR DESCRIPTION
**Pull request by npdoty**
alternative resolution for issue #1

### CODE REVIEW

**Comment by AramZS** [comment]
Just to double check @npdoty this is supposed to be a #10 **or** #9 question, not both?

**Comment by npdoty** [comment]
Yes, #9 and #10 are conflicting: the resolution to #1 would be to pick one or neither, but not both.

**Comment by martinthomson** [comment]
I'm happier with #9.  Elections are terrible, but I'd rather not open a path to appeals to a higher authority.

**Comment by npdoty** [comment]
> Elections are terrible, but I'd rather not open a path to appeals to a higher authority.

Fwiw, the option to ask the Community Development Lead to intervene is also in the current text (and remains in the #9 text), for cases where someone is unsatisfied with the outcome of an election. 🤷🏻

**Comment by ekr** [comment]
Well, then we should remove the community development lead text. We should be moving in the direction of democracy, not away.

**Comment by seanturner** [comment]
Going with #9 modified to be 3 months.

**Pull request closed without merging**
